// <auto-generated />
using System;
using JobMicroservice.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobMicroservice.Migrations
{
    [DbContext(typeof(JobDbContext))]
    [Migration("20221201132311_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobMicroservice.Entities.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DueDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ecm")
                        .HasColumnType("int");

                    b.Property<string>("Engineer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Finished")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gpdm")
                        .HasColumnType("int");

                    b.Property<string>("JobDescription")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Received")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Started")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("System")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhenComplete")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JobId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            JobId = 1,
                            Client = "TOYOTA",
                            Ecm = 4561976,
                            Engineer = "Agata",
                            Gpdm = 1,
                            JobDescription = "Create drawing",
                            Link = "linkt o task",
                            ProjectName = "sap text",
                            ProjectNumber = "LASDl",
                            Received = "15.22.2022",
                            Status = "2D",
                            System = "Catia",
                            Type = "2D"
                        },
                        new
                        {
                            JobId = 2,
                            Client = "TOYOTA",
                            DueDate = "25.11.2022",
                            Ecm = 4561976,
                            Engineer = "Agata",
                            Gpdm = 1,
                            JobDescription = "Create drawing",
                            Link = "linkt o task",
                            ProjectName = "sap text",
                            ProjectNumber = "LASDl",
                            Received = "20.11.2022",
                            Status = "2D",
                            System = "Catia",
                            Type = "2D"
                        },
                        new
                        {
                            JobId = 3,
                            Client = "TOYOTA",
                            Ecm = 4561976,
                            Engineer = "Agata",
                            Gpdm = 1,
                            JobDescription = "Create drawing",
                            Link = "linkt o task",
                            ProjectName = "sap text",
                            ProjectNumber = "LASDl",
                            Received = "20.11.2022",
                            Status = "2D",
                            System = "Catia",
                            Type = "2D"
                        });
                });

            modelBuilder.Entity("JobMicroservice.Entities.UserJob", b =>
                {
                    b.Property<int>("UserJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserJobId"));

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserJobId");

                    b.HasIndex("JobId");

                    b.ToTable("UserJobs");
                });

            modelBuilder.Entity("JobMicroservice.Entities.UserJob", b =>
                {
                    b.HasOne("JobMicroservice.Entities.Job", "Job")
                        .WithMany("UserJobs")
                        .HasForeignKey("JobId");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobMicroservice.Entities.Job", b =>
                {
                    b.Navigation("UserJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
